# Generated by Django 3.2.25 on 2025-07-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_ages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_names',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_class',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First Class', 'First Class')], default='Economy', max_length=20),
        ),
    ]
